// UI Actions
export const UI_FRIDGE_SET_PROFILE = "UI_FRIDGE_SET_PROFILE";
export const UI_FRIDGE_SET_LIST = "UI_FRIDGE_SET_LIST";
export const UI_AUTH_SET_SPLASH = "UI_AUTH_SET_SPLASH";
export const UI_AUTH_SET_LOGIN = "UI_AUTH_SET_LOGIN";
export const UI_AUTH_SET_REGISTER = "UI_AUTH_SET_REGISTER";
export const UI_AUTH_SET_AUTHENTICATED = "UI_AUTH_SET_AUTHENTICATED";

// User Actions
export const USER_GET_INFO = "USER_GET_INFO";
export const USER_GET_PRODUCTS = "USER_GET_PRODUCTS";
export const USER_ADD_PRODUCT = "USER_ADD_PRODUCT";
export const USER_DELETE_PRODUCT = "USER_DELETE_PRODUCT";
export const USER_PRODUCTS_LOADING = "USER_PRODUCTS_LOADING";

// Group Actions
export const GROUP_GET_INFO = "GROUP_GET_INFO";
export const GROUP_GET_USERS = "GROUP_GET_USERS";
export const GROUP_GET_PRODUCTS = "GROUP_GET_PRODUCTS";
export const GROUP_USERS_LOADING = "GROUP_USERS_LOADING";
export const GROUP_PRODUCTS_LOADING = "GROUP_PRODUCTS_LOADING";
