// UI Actions
export const UI_FRIDGE_SET_PROFILE = 'UI_FRIDGE_SET_PROFILE';
export const UI_FRIDGE_SET_LIST = 'UI_FRIDGE_SET_LIST';
export const UI_AUTH_SET_SPLASH = 'UI_AUTH_SET_SPLASH';
export const UI_AUTH_SET_LOGIN = 'UI_AUTH_SET_LOGIN';
export const UI_AUTH_SET_REGISTER = 'UI_AUTH_SET_REGISTER';
export const UI_AUTH_SET_AUTHENTICATED = 'UI_AUTH_SET_AUTHENTICATED';